Adding binance api
fioricino/xmb pull request #3
Opened 2018-01-29 16:56 UTC by Realhedin

binance api from:
https://support.binance.com/hc/en-us/articles/115003235691-Binance-API-Trading-Rules
https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

2018-01-30 15:31 UTC, fioricino requested changes

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +            newData = BinanceApi._create_exmo_open_orders(self,data)
Make method static or call without "self" argument

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +        except KeyError:
there'll be no KeyError in this call

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +                if order['status'] is 'CANCELED':
is -> ==

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +            return []
KeyError will be thrown if there's no 'status' key in returned data. It means that smth went very wrong. Sp it's better not to catch any exception here so that it's handled in calling code.

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +    def is_order_partially_completed(self, currency_1, currency_2, order_id):
There are no parameters currency_1 and currency_2 in the original interface. Let's hardcode them in this class for the beginning. Later we'll adjust original interface.

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +    def cancel_order(self, currency_1, currency_2, order_id):
There are no parameters currency_1 and currency_2 in the original interface. Let's hardcode them in this class for the beginning. Later we'll adjust original interface.

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +    def get_trades(self, currency_1, currency_2):
It's ok for the first time, but later we must rewrite this methos so that t can use a proxy (see exmo_api_proxy), because it will be called very often.

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +            if 'error' in obj and obj['error']:
Please check that api really returns error responses in this format. (Does the response really have attributes 'error' and 'code'?)

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +        return int(round(time.time() * 1000))
Maybe server error response about wrong timestamp is caused by this rounding? Maybe you must use floor? Or round before multiplying?

2018-01-30 15:31 UTC, fioricino commented on binance_api.py
> +            if 'error' in obj and obj['error']:
Looks like you provide this format in converter.

2018-01-31 18:50 UTC, Realhedin commented on binance_api.py
> +            newData = BinanceApi._create_exmo_open_orders(self,data)
done

2018-01-31 18:51 UTC, Realhedin commented on binance_api.py
> +                if order['status'] is 'CANCELED':
done

2018-01-31 18:51 UTC, Realhedin commented on binance_api.py
> +        except KeyError:
done

2018-01-31 18:53 UTC, Realhedin commented on binance_api.py
> +    def is_order_partially_completed(self, currency_1, currency_2, order_id):
done

2018-01-31 18:57 UTC, Realhedin commented on binance_api.py
> +            return []
done

2018-01-31 18:57 UTC, Realhedin commented on binance_api.py
> +    def cancel_order(self, currency_1, currency_2, order_id):
done

2018-01-31 19:01 UTC, Realhedin commented on binance_api.py
> +        return int(round(time.time() * 1000))
removed

2018-01-31 19:30 UTC, fioricino approved these changes

2018-01-31 19:30 UTC, merged